# Generated by Django 5.0.6 on 2024-08-19 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meaning', models.TextField(default=None)),
                ('extended_meaning', models.TextField(blank=True, default=None, null=True)),
                ('morphology', models.TextField(blank=True, default=None, null=True)),
                ('poster', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('search_hits', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_seen', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
